config/routes.rb
FunnyApp::Application.routes.draw do
  
  root 'app/feeds#index'
  
  namespace :cms do
    get "home/index"
    resources :feeds, only: [:index]
    
    get "import/form_all_in_html_pinterest"
    post "import/parse_all_in_html_pinterest"
  end
  
  namespace :app do
    resources :feeds, only: [:index] do
      get 'random_feeds', on: :collection
      post 'rate_up', on: :member
      post 'rate_down', on: :member
    end
  end

  

end

app/controllers/cms/feeds_controller.rb
class Cms::FeedsController < ApplicationController
  layout "cms"
  
  def index
    @feeds = Feed.includes(:tags, :images).order('id DESC').paginate(:page => params[:page], :per_page => 50)
  end

end

app/controllers/cms/home_controller.rb
class Cms::HomeController < ApplicationController
  layout "cms"
  def index
  end
end

app/controllers/cms/import_controller.rb
class Cms::ImportController < ApplicationController
  layout "cms"
  def form_all_in_html_pinterest
    
  end
  
  def parse_all_in_html_pinterest
    tags = Tag.where(name: params[:tags])
    Collectors::PinterestCollector.new.parse_all_in_html(params[:html], tags)
    redirect_to cms_feeds_url 
  end
end

app/helpers/cms/feeds_helper.rb
module Cms::FeedsHelper
end

app/helpers/cms/home_helper.rb
module Cms::HomeHelper
end

app/views/layouts/cms/_messages.html.erb
<%
# Render the flash messages into div tags
#
# Example Bootstrap alerts - http://getbootstrap.com/components/#alerts
#<div class="alert alert-success" role="alert">...</div>
#<div class="alert alert-info" role="alert">...</div>
#<div class="alert alert-warning" role="alert">...</div>
#<div class="alert alert-danger" role="alert">...</div>
unless flash.nil?
	flash.each do |k,v|
%>
<div class="alert <%= k %> <%= alert_class(k) %> alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
<%		if v.kind_of?(Array) %>
	<ul>
<%			v.each do |i| %>
		<li><%= i %></li>
<%      	end %>
	</ul>
<%     else %>
	<p><%= v %></p>
<%     end %>
</div>
<%	end %>
<% end %>

app/views/layouts/cms/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Funny App | CMS".html_safe, cms_home_index_path, class: "navbar-brand" %>
		</div>
		<div id="navbar" class="navbar-collapse collapse navbar-right">
			<ul class="nav navbar-nav">	
				<li><%= link_to "Home", cms_home_index_path %></li>	
				<li><%= link_to "Feeds", cms_feeds_path %></li>	
				<li class="dropdown1">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Import <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><%= link_to "Pinterest: All in Html", cms_import_form_all_in_html_pinterest_path %></li>
					</ul>
				</li>
			</ul>
		</div> 
	</div>
</nav>