config/routes.rb
FunnyApp::Application.routes.draw do
  
  root 'app/feeds#index'
  
  namespace :cms do
    get "home/index"
    resources :feeds, only: [:index]
    
    get "import/form_all_in_html_pinterest"
    post "import/parse_all_in_html_pinterest"
  end
  
  namespace :app do
    resources :feeds, only: [:index] do
      get 'random_feeds', on: :collection
      post 'rate_up', on: :member
      post 'rate_down', on: :member
    end
  end

  

end

app/controllers/cms/feeds_controller.rb
class Cms::FeedsController < ApplicationController
  layout "cms"
  
  def index
    @feeds = Feed.includes(:tags, :images).order('id DESC').paginate(:page => params[:page], :per_page => 50)
  end

end

app/controllers/cms/home_controller.rb
class Cms::HomeController < ApplicationController
  layout "cms"
  def index
  end
end

app/controllers/cms/import_controller.rb
class Cms::ImportController < ApplicationController
  layout "cms"
  def form_all_in_html_pinterest
    
  end
  
  def parse_all_in_html_pinterest
    tags = Tag.where(name: params[:tags])
    Collectors::PinterestCollector.new.parse_all_in_html(params[:html], tags)
    redirect_to cms_feeds_url 
  end
end

app/helpers/cms/feeds_helper.rb
module Cms::FeedsHelper
end

app/helpers/cms/home_helper.rb
module Cms::HomeHelper
end

app/views/cms/import/form_all_in_html_pinterest.html.erb
<div class="container">
	<div class="form_container">
	<%= bootstrap_form_tag url: cms_import_parse_all_in_html_pinterest_url do |f| %>
	<%= f.text_area :html, rows: 40 %>
	<%= f.select(:tags, options_for_select(Tag.all.collect{|t| t.name}), {}, {:multiple => true}) %>
	<%= f.submit %>
	<% end %>
	</div>
</div>